### ISSUE TITLE
Basic usage produces corrupt YUV file

### ISSUE THREAD

**Issue by shawnbissell** [stunpix/yuvit#12]
I'm just trying to get yuvit to convert simple test jpg files, but when I view them using imagemagicks "display" or YUVToolKit on my mac they seem to be corrupted. I've compiled the current master version on ubuntu 12.04 against the ubuntu distributed FreeImage 3.15 as well as the latest 3.16 from source. I also tried using your v0.1 tag with the FreeImage included with that version. 

The command i'm running is:
user@ubuntu-pangolin:~/yuvit/build/src$ ./yuvit -o 640x480.yuv ../../images/640x480.jpg 

In all cases the YUV seems to have the colours distorted and horizontal line across it.
Here is a screenshot of what they look like on my mac. 

![corruptyuv](https://cloud.githubusercontent.com/assets/831982/6239772/fef3fbc2-b6bb-11e4-9afd-bfa5097e6f07.png)

github doesn't support the uploading of the yuv itself so let me know if you want to see it and where to send it. I'm guessing its a FreeImage/Ubuntu specific problem so let me know if you need anything else.

**Comment by stunpix** [comment]
Hi. Images aren't corrupted. By default yuvit tool converts images to planar yuv format without doing a sampling (scaling) for uv components, meanwhile YUV Toolkit (from screenshot) by default reads images as [I420]: planar yuv, where uv components are sampled horizontally+vertically and uv planes are swapped in order. To convert images to format that YUV Toolkit will understand with default settings, you should convert them using following options:
[I420]: http://www.fourcc.org/yuv.php#IYUV

    yuvit -o 640x480.yuv -s h2v2 -w ../../images/640x480.jpg

So it's just a mismatch between default input/output formats.

**Comment by shawnbissell** [comment]
Great it worked! Thanks for the link to the YUV formats as well, that cleared up a lot of things for me.

One other related issue I ran into was converting png8 images into any format doesn't seem to work correctly. They are corrupted differently than the first issue I had. I tested with the PngSuite test images found here http://www.schaik.com/pngsuite/pngsuite_bas_png.html
and got some strange results trying to convert to I420 planer yuv
```
yuvit -o basn3p02_32x32.yuv -s h2v2 -w basn3p02.png 
yuvit -o basn6a08_32x32.yuv -s h2v2 -w basn6a08.png 
```
![screenshot 2015-02-19 12 28 26](https://cloud.githubusercontent.com/assets/831982/6275346/2e145f46-b833-11e4-95ee-cced594c6987.png)
![screenshot 2015-02-19 12 31 55](https://cloud.githubusercontent.com/assets/831982/6275363/51bc2712-b833-11e4-99ad-c449117607e6.png)

I'm guessing the input type is not being detected correct by FreeImage or?

**Comment by shawnbissell** [comment]
Correction, it seems to be all PNG image types. The second one above there there is actually a 8bit Truecolor with alpha PNG.

**Comment by stunpix** [comment]
Confirm. Tool handles input images with color depth other than 24bpp incorrectly. I'm preparing a patch.

**Comment by shawnbissell** [comment]
Great thank you!

**Comment by stunpix** [comment]
Changes are pushed, you can pull them and try.

**Comment by shawnbissell** [comment]
Yes it worked. Thank you!
